# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

    - task: UseDotNet@2
      displayName: ".NET Core 3.1.x"
      inputs:
        version: '3.1.x'
        packageType: sdk
    - script: dotnet build ./src/Calculator/Calculator.sln
      displayName: 'dotnet build'

    - task: DotNetCoreCLI@2
      displayName: "Test"
      inputs:
        command: 'test'
        arguments:  './src/Calculator/Calculator.UnitTest/Calculator.UnitTest.csproj'

    - task: DotNetCoreCLI@2
      displayName: "Publish"
      inputs:
        command: 'publish'
        publishWebProjects: false
        arguments: './src/Calculator/Calculator.sln -r linux-x64 --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true

    - task: PublishBuildArtifacts@1
      displayName: "Upload Artifacts"
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
        artifactName: 'publish' 